### ISSUE TITLE
airgeddon does not work properly when concurrent mode is enabled

### ISSUE THREAD

**Issue by LuckyFishGeek** [morrownr/8812au-20210629#25]
iw dev :
![Snipaste_2021-12-28_09-56-54](https://user-images.githubusercontent.com/29472751/147519270-743cbd53-0385-49a1-9cf5-d22a8ddbc806.png)

When I select wlan0 as the device, I can scan and attack, but can't establish a phishing hotspot and start gon correctly
![Snipaste_2021-12-28_09-52-57](https://user-images.githubusercontent.com/29472751/147519343-de6aff8f-fe36-4779-9e70-3aa1de691291.png)

When I select wlan1 as the device, it can only scan but not attack

Can this issue be further addressed?

Very much looking forward to it.

Thank you for your work.

**Comment by usama7628674** [comment]
Concurrent mode does not work as you would expect it to work with other adapters from different chipset manufacturer. The reason is Realtek does not support virtual interface because the driver does not get written for `mac80211`. To launch an evil twin attack you need to get a second adapter or an adapter that supports a virtual interface.

**Comment by usama7628674** [comment]
More info here #9
